before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    main: ./cmd/gh-bump
archives:
  - name_template: '{{ .Os }}-{{ .Arch }}'
    format: binary
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  skip: true
