name: test
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: build & test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: build
        run: go build .
      - name: test
        # We would like to use -race option but promptui has a data race bug, so we don't use it.
        run: go test -v -coverprofile="coverage.txt" -covermode=atomic ./...
      - name: upload coverage to codecov
        uses: codecov/codecov-action@v3
